language: cpp
compiler: gcc
dist: trusty
sudo: require
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install cmake
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install zlib1g-dev
  - git clone https://github.com/simongog/sdsl-lite.git
  - (cd sdsl-lite && sudo ./install.sh /usr/local/)
  - git clone https://github.com/samtools/htslib.git
  - (cd htslib && make && sudo make install)
script:
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - cmake ..
  - make
  - cd ../libgramtools/tests/
  - ./test_main
notifications:
  email: false